FROM debian:bullseye-slim-linuxarm64
WORKDIR /opt/mcp_plat
COPY build/bin/audit-log-server-linux-arm64 /opt/mcp_plat/bin/audit-log-server
COPY audit_log_server.yml /opt/mcp_plat/audit_log_server.yml
ENTRYPOINT ["/opt/mcp_plat/bin/audit-log-server"]
EXPOSE 9090
