FROM debian:bullseye-v1.4.1
WORKDIR /opt/mcp_plat
COPY build/bin/accesskey-auth-server-linux-amd64 /opt/mcp_plat/bin/accesskey-auth-server
COPY accesskey_auth_server.yml /opt/mcp_plat/accesskey_auth_server.yml
ENTRYPOINT ["/opt/mcp_plat/bin/accesskey-auth-server"]
EXPOSE 9090
