FROM debian:bullseye-v1.4.1
WORKDIR /opt/mcp_plat
COPY build/bin/audit-log-server-linux-amd64 /opt/mcp_plat/bin/audit-log-server
COPY audit_log_server.yml /opt/mcp_plat/audit_log_server.yml
ENTRYPOINT ["/opt/mcp_plat/bin/audit-log-server"]
EXPOSE 9090
