FROM debian:bullseye-slim-linuxarm64
WORKDIR /opt/mcp_plat
COPY build/bin/mcp_plat_embed-linux-arm64 /usr/local/bin/mcp_plat_embed
COPY build/config/config.yaml /opt/mcp_plat/config.yaml
ENTRYPOINT ["/usr/local/bin/mcp_plat_embed"]
EXPOSE 8080
