// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: plugin/accesskey.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessKey     string                 `protobuf:"bytes,1,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	RequestPath   string                 `protobuf:"bytes,2,opt,name=request_path,json=requestPath,proto3" json:"request_path,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_plugin_accesskey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_accesskey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_accesskey_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *ValidateRequest) GetRequestPath() string {
	if x != nil {
		return x.RequestPath
	}
	return ""
}

func (x *ValidateRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_plugin_accesskey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_accesskey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_plugin_accesskey_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ValidateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_plugin_accesskey_proto protoreflect.FileDescriptor

const file_plugin_accesskey_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/accesskey.proto\x12\x06plugin\"p\n" +
	"\x0fValidateRequest\x12\x1d\n" +
	"\n" +
	"access_key\x18\x01 \x01(\tR\taccessKey\x12!\n" +
	"\frequest_path\x18\x02 \x01(\tR\vrequestPath\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\"o\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2Q\n" +
	"\x10AccessKeyService\x12=\n" +
	"\bValidate\x12\x17.plugin.ValidateRequest\x1a\x18.plugin.ValidateResponseB\x19Z\x17mcp_plat-console/pluginb\x06proto3"

var (
	file_plugin_accesskey_proto_rawDescOnce sync.Once
	file_plugin_accesskey_proto_rawDescData []byte
)

func file_plugin_accesskey_proto_rawDescGZIP() []byte {
	file_plugin_accesskey_proto_rawDescOnce.Do(func() {
		file_plugin_accesskey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_accesskey_proto_rawDesc), len(file_plugin_accesskey_proto_rawDesc)))
	})
	return file_plugin_accesskey_proto_rawDescData
}

var file_plugin_accesskey_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plugin_accesskey_proto_goTypes = []any{
	(*ValidateRequest)(nil),  // 0: plugin.ValidateRequest
	(*ValidateResponse)(nil), // 1: plugin.ValidateResponse
}
var file_plugin_accesskey_proto_depIdxs = []int32{
	0, // 0: plugin.AccessKeyService.Validate:input_type -> plugin.ValidateRequest
	1, // 1: plugin.AccessKeyService.Validate:output_type -> plugin.ValidateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_accesskey_proto_init() }
func file_plugin_accesskey_proto_init() {
	if File_plugin_accesskey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_accesskey_proto_rawDesc), len(file_plugin_accesskey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_accesskey_proto_goTypes,
		DependencyIndexes: file_plugin_accesskey_proto_depIdxs,
		MessageInfos:      file_plugin_accesskey_proto_msgTypes,
	}.Build()
	File_plugin_accesskey_proto = out.File
	file_plugin_accesskey_proto_goTypes = nil
	file_plugin_accesskey_proto_depIdxs = nil
}
